### ISSUE TITLE
Galactic Release?

### ISSUE THREAD

**Issue by cco-seasony** [anqixu/ueye_cam#117]
Hey! 
Any updates on a ROS2 Galactic release?

I am trying to build the foxy branch in galactic and basically debugging whatever comes up to make it work. Unfortunately we do not have the resources to do the full porting.

Thanks in advance!
Carlos

**Comment by jmackay2** [comment]
I took a quick look at this and fixed a few of the bugs for Galactic (that should have been fixed in Foxy anyway). It now technically builds if you remove the `-Werror` flag in the `CMakeLists.txt`. 

Here are the two remaining warnings:

-  format security of `std::string` as a format string which is warned about in the [Galactic release page](https://docs.ros.org/en/galactic/Releases/Release-Galactic-Geochelone.html#change-in-rclcpp-s-logging-macros)
- rclcpp::Duration deprecation

**Comment by cco-seasony** [comment]
Hey! thanks for the reply.
I managed to fix the issues too but forgot to close the issue!
In any case, thanks a lot for taking the time.
