### ISSUE TITLE
arduino board for hardware synchronization for 2 ueye camera

### ISSUE THREAD

**Issue by Annaiyan** [anqixu/ueye_cam#49]
hello,

i would like to develop the hardware synchronized  stereo camera using two ueye camera.But don't know which hardware board i have to buy.
is tinyduino board compatible for my case. (https://tinycircuits.com/pages/tinyduino-overview).

any specific recommendations of hardware board for developing the stereo camera to use the ueye_cam package ?

thanks in advance

**Comment by anqixu** [comment]
The minimal hardware requirement to synchronize 2 uEye cameras is to connect the flash output pin from one camera to the other's trigger input pin. Then in software you need to ensure that the slave camera triggers on rising edge (LO_HI) rather than on falling edge (HI_LO).

I used an Arduino to implement a NOR gate between 4 cameras in our robot, because we wanted to be able to let any subset of cameras operate in synchronous mode. If this feature is useful for you, then any Arduino microcontroller with 2*N digital I/O pins will do the trick. So if you want to use a tinyduino, you will also need a Proto Board to solder the flash output and digital input pins from every one of your uEye cameras. Note that [my sample arduino code](https://github.com/anqixu/duino_projects/blob/master/ueye_cam_ext_trigger/ueye_cam_ext_trigger.ino) is very generic, and should work with any Arduino-compatible micro-processors. You can alternatively implement a NOR gate logic yourself on any other uP.
