### ISSUE TITLE
Targeting the new IDS Software Suite 4.94.00 for Linux

### ISSUE THREAD

**Issue by shac12** [anqixu/ueye_cam#85]
Hi,

Is it possible to use the new driver set with this package ? If so how would I go about doing so ? It explicitly supports the camera that we are using and so having it natively supported through ROS would be amazing. 

We are using the UI-388xLE VU AF
More details can be found here: 

https://en.ids-imaging.com/files/downloads/knowledgebase/pdf/release_note/en_gb/release-notes-ids-software-suite-4-94.pdf

Kind regards,
Sharif

**Comment by anqixu** [comment]
I hope to have time next weekend to make the upgrade. The process is quite manual unfortunately: I remember needing to extract selective content from IDS package and re-zip, ask someone at ROS to upload to their servers, then update the URL. I need to do this anyway soon because the latest ARM packages keep fail to build.
